remember_window_size no
remember_window_position no
initial_window_width 800
initial_window_height 600

font_family Adwaita Mono

background #141414

active_border_color #359bb8
window_border_width 0.5pt
window_margin_width 1.5
draw_window_borders_for_single_window yes
window_padding_width 0.5

enabled_layouts Tall, *

tab_bar_style powerline
tab_powerline_style slanted

active_tab_foreground #000000
active_tab_background #359bb8
inactive_tab_foreground #000000
inactive_tab_background #216d82

selection_background #79c3d8
selection_foreground #000000

tab_bar_min_tabs 1

dynamic_background_opacity yes
background_opacity 0.7
background_tint 1
enable_background_blur yes
background_blur 1

enable_audio_bell no
