preload = ~/Pictures/Wallpapers/pat.png
preload = ~/Pictures/Wallpapers/5120x2880.png
wallpaper {
	monitor = DP-1
	path = ~/Pictures/Wallpapers/5120x2880.png
	fit_mode = cover
}

wallpaper {
	monitor = HDMI-A-1
	path = ~/Pictures/Wallpapers/5120x2880.png
	fit_mode = cover
}

splash = false
