### MY PROGRAMS ###
$terminal = kitty
$fileManager = pcmanfm
$menu = rofi --show drun


### AUTOSTART ###
exec-once = mako
exec-once = ~/.config/waybar/launch.sh
exec-once = hyprpaper
exec-once = rofi -show drun


### ENVIRONMENT VARIABLES ###
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct

env = ELECTRON_OZONE_PLATFORM_HINT,auto

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

#for libadwaita gtk4 apps you can use this command:
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps

#for gtk3 apps you need to install adw-gtk3 theme (in arch linux sudo pacman -S adw-gtk-theme)
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"   # for GTK3 apps


### PERMISSIONS ###
# See https://wiki.hypr.land/Configuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow


### LOOK AND FEEL ###
source = ~/.config/hypr/style.conf


### INPUT ###
source = ~/.config/hypr/input.conf


### KEYBINDINGS ###
source = ~/.config/hypr/binds.conf


### WINDOWS AND WORKSPACES ###
source = ~/.config/hypr/desktop.conf
